services:
  app-db:
    image: postgres:17.10-bookworm
    container_name: app-db
    command: ["postgres", "-c", "timezone=Asia/Ho_Chi_Minh"]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - ../app-db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ../app-db/sample-data.sql:/docker-entrypoint-initdb.d/sample-data.sql
      - postgres_data-dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - unihub-workshop-network-dev

  app-redis:
    image: redis:8.8.0-alpine3.23
    container_name: app-redis
    ports:
      - "6379:6379"
    networks:
      - unihub-workshop-network-dev

  bff-redis:
    image: redis:8.8.0-alpine3.23
    container_name: bff-redis
    ports:
      - "6380:6379"
    networks:
      - unihub-workshop-network-dev

  service-auth:
    image: quay.io/keycloak/keycloak:26.7.0
    container_name: service-auth
    ports:
      - "8080:8080"
    env_file:
      - ../service-auth/.env
    environment:
      - KC_HOSTNAME=localhost
      - KC_HTTP_RELATIVE_PATH=/auth
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
      - KC_DB_URL=jdbc:postgresql://app-db:5432/postgres
      - KC_DB=postgres
    volumes:
      - ../service-auth/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    command: start-dev --import-realm
    depends_on:
      - app-db
    networks:
      - unihub-workshop-network-dev

volumes:
  postgres_data-dev: {}

networks:
  unihub-workshop-network-dev: {}
