server:
  port: ${SERVER_PORT}

spring:
  application:
    name: gateway-bff
  jackson:
    time-zone: Asia/Ho_Chi_Minh

  threads:
    virtual:
      enabled: true

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI}

  config:
    import: optional:file:./.env[.properties]

app:
  gateway:
    rate-limit:
      replenish-rate: 10
      burst-capacity: 20
      requested-tokens: 1
