plugins {
    id 'java'
}

group = 'com.github.hownameee'
version = '0.0.1-SNAPSHOT'
description = 'UniHub Workshop Summary PDF System'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
}

tasks.named('test') {
    useJUnitPlatform()
}
