worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
    access_log  /var/log/nginx/access.log  main;
    error_log   /var/log/nginx/error.log warn;

    sendfile        on;
    keepalive_timeout  65;

    # rate is set to 100 requests per second.
    limit_req_zone $binary_remote_addr zone=ip_limit:10m rate=100r/s;

    # Upstream cluster for Gateway BFF instances
    upstream bff_cluster {
        server gateway-bff:8081;
    }

    server {
        listen 80;
        server_name localhost;

        # burst=20 allows bursts up to 20 requests above the rate limit.
        # nodelay rejects requests exceeding the burst limit immediately with 503.
        limit_req zone=ip_limit burst=20 nodelay;

        # proxy headers
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Route /auth (Keycloak IAM)
        location /auth {
            proxy_pass http://service-auth:8080;
        }

        # Route /api (BFF Gateway Cluster)
        location /api {
            proxy_pass http://bff_cluster;
            proxy_next_upstream error timeout http_502 http_503 http_504;
            proxy_connect_timeout 5s;
            proxy_read_timeout 60s;
        }

        # Route / (React SPA served by the frontend NGINX)
        location / {
            proxy_pass http://app-frontend:80;
        }
    }
}
